version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=255724
      - DB_NAME=phonebook
      - DB_CHARSET=utf8mb4
      - DB_COLLATION=utf8mb4_unicode_ci
    command: bash -c "
      ./wait-for-mysql.sh db
      && python /app/app.py"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 255724
      MYSQL_DATABASE: phonebook
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: